// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChwLsZCxSrjjccBC3wO8FnlP1LSYPGlw0',
    appId: '1:77010199551:web:6d4ad1c01fb9d9e2fb3dca',
    messagingSenderId: '77010199551',
    projectId: 'aalaapp-5c914',
    authDomain: 'aalaapp-5c914.firebaseapp.com',
    storageBucket: 'aalaapp-5c914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKR1qHfCBgf_ZmKt6qhpkhpaABcFZRk_I',
    appId: '1:77010199551:android:78bdd603e4653da3fb3dca',
    messagingSenderId: '77010199551',
    projectId: 'aalaapp-5c914',
    storageBucket: 'aalaapp-5c914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXvHBbk0FuZkeixJ7Lhc3kE5WZBI-JqQ',
    appId: '1:77010199551:ios:60f7557888424606fb3dca',
    messagingSenderId: '77010199551',
    projectId: 'aalaapp-5c914',
    storageBucket: 'aalaapp-5c914.appspot.com',
    iosBundleId: 'com.example.aala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeXvHBbk0FuZkeixJ7Lhc3kE5WZBI-JqQ',
    appId: '1:77010199551:ios:add20faa8669d73cfb3dca',
    messagingSenderId: '77010199551',
    projectId: 'aalaapp-5c914',
    storageBucket: 'aalaapp-5c914.appspot.com',
    iosBundleId: 'com.example.aala.RunnerTests',
  );
}
